### ISSUE TITLE
Add tick controller class to game

### ISSUE THREAD

**Issue by BBurton0** [cyberbitgame/cyberbitgame#12]
This should allow us to do something every so often. It'll also allow us to globally control when a tick-update should happen.

**Comment by sarvsav** [comment]
Closing this, as it should be in ToDO list or create a new file named TaskList. It's not an issue. Maintain a separate task list for this. This section is for only issue/bug tracking.

**Comment by sarvsav** [comment]
Reopened, as issues will help help us in managing milestones,

**Comment by sarvsav** [comment]
We will use website private link to track features or Text file. Closing it.
