### ISSUE TITLE
Create animation controller

### ISSUE THREAD

**Issue by BBurton0** [cyberbitgame/cyberbitgame#13]
When re-rendering the map, if a rendered/to-be-rendered is a sprite with a known animation, give ability to change frames via function calls.

This should allow us to call a frame-switch function every so many ticks.

**Comment by sarvsav** [comment]
Closing this, as it should be in ToDO list or create a new file named TaskList. It's not an issue. Maintain a separate task list for this. This section is for only issue/bug tracking.

**Comment by sarvsav** [comment]
Reopened, as issues will help help us in managing milestones,

**Comment by sarvsav** [comment]
We will use website private link to track features or Text file. Closing it.
