### ISSUE TITLE
lSDL_ttf, lSDL_mixer, lSDL_image missing.

### ISSUE THREAD

**Issue by sarvsav** [cyberbitgame/cyberbitgame#8]
The following error message appeared on screen during the process of make.

```
/usr/bin/ld: cannot find -lSDL_image
/usr/bin/ld: cannot find -lSDL_ttf
/usr/bin/ld: cannot find -lSDL_mixer
collect2: error: ld returned 1 exit status
make[2]: *** [libCyberbitGame.la] Error 1
make[2]: Leaving directory `/home/maddy/Project/cyberbitgame/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/maddy/Project/cyberbitgame/src'
make: *** [all-recursive] Error 1
```

**Comment by BBurton0** [comment]
I got this error as well. I am able to compile after installing SDL_image, SDL_image-devel, SDL_mixer, SDL_mixer-devel, SDL_ttf, and SDL_ttf-devel.

**Comment by sarvsav** [comment]
Well, Thanks for confirming it. Kindly add this in "how to build" process in "README.md" file in your next pull request, till then i will keep this issue open.

**Comment by sarvsav** [comment]
This is resolved. Closing it.
